services:
  mdl-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - mdl-db
    
  mdl-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: moodle_admin
      POSTGRES_PASSWORD: moodle_psql
      POSTGRES_DB: moodle_db
    volumes:
      - ./mdl-db:/var/lib/postgresql/data

  mdl-nginx-conf:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - mdl-app

volumes:
  mdl-db: